### ISSUE TITLE
Computable 0.1.0 Security

### ISSUE THREAD

**Issue by rbharath** [computablelabs/contracts#37]
Let's use this issue to track security changes we'll need to make to leading up to the 0.1.0 release.

- [ ] Swap to ERC20 OpenZeppelin contracts #36 
- [ ] Decide whether we are going to upgrade to solidity 0.5 for the 0.1.0 release #35 
- [ ] Have thorough unit test coverage of contracts in repo. Aim: 80ish percent. #38 

Will modify this list as clarity emerges around our needs.
